### ISSUE TITLE
Broken for chrome

### ISSUE THREAD

**Issue by abuzakaria** [jvns/jvns.ca#16]
Website is broken for chrome. Shows source html.

**Comment by shavs** [comment]
Hi! This has recently been talked about by [Julia on the blog itself](https://www.jvns.ca/blog/2018/09/03/editing-my-blog-s-http-headers-with-cloudflare-workers/). Hopefully, this has already been fixed by Julia, but if it hasn't, please feel free to respond, or get in contact with [Julia directly via Twitter](https://twitter.com/b0rk).

Does it still show the source in Google Chrome for you currently? Currently, using Firefox (v62) and Google Chrome (v69), I can't see the original source HTML without prefixing the URL with `view-source:`.

**Comment by abuzakaria** [comment]
Read the blog. Works now.
